<div id="content">
    <?php
        if(isset($_GET['quanly'])){
            $tam=$_GET['quanly'];
        }
        else{
            $tam='';
        }
        if($tam=='quanlyloaisp'){
            include('modules/quanlyloaisp/main.php');
        }
        if($tam=='quanlysp'){
            include('modules/quanlysp/main.php');
        }
        if($tam=='quanlynsx'){
            include('modules/quanlynhasx/main.php');
        }
    ?>
</div>